name: Screenshots

on: deployment_status

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.deployment_status.id }}

jobs:
  devices:
    name: Capture multi devices
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"

      - name: Take screenshots
        uses: flameddd/screenshots-ci-action@master
        with:
          url: ${{ github.event.deployment_status.target_url }}
          devices: iPhone 14, iPhone 14 landscape

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: screenshots
          name: test-screenshots
